# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/element/Rectangle.hpp \
    ./src/element/CalendarObjectFactory.hpp \
    ./src/element/Month.hpp \
    ./src/command/ResizeCalendar.hpp \
    ./src/command/UndoHistory.hpp \
    ./src/element/Line.hpp \
    ./src/command/AddObject.hpp \
    ./src/command/Command.hpp \
    ./src/command/RemoveObject.hpp \
    ./src/element/CustomListWidgetItem.hpp \
    ./src/element/Element.hpp \
    ./src/window/SimpleCalendarCreator.hpp \
    ./src/window/object_editor/EditLine.hpp \
    ./src/command/object_properties_modifier/LineObject.hpp \
    ./src/window/PreviewWindow.hpp \
    ./src/window/CalendarResizer.hpp \
    ./src/window/ObjectCreator.hpp \
    ./src/window/object_editor/EditRectangle.hpp \
    ./src/command/ChangeObjectProperties.hpp
SOURCES += ./src/command/object_properties_modifier/LineObject.cpp \
    ./src/element/CalendarObjectFactory.cpp \
    ./src/element/Rectangle.cpp \
    ./src/window/object_editor/EditLine.cpp \
    ./src/command/ResizeCalendar.cpp \
    ./src/command/UndoHistory.cpp \
    ./src/element/Month.cpp \
    ./src/window/CalendarResizer.cpp \
    ./src/element/Line.cpp \
    ./src/window/ObjectCreator.cpp \
    ./src/command/AddObject.cpp \
    ./src/command/RemoveObject.cpp \
    ./src/element/CustomListWidgetItem.cpp \
    ./src/main.cpp \
    ./src/window/PreviewWindow.cpp \
    ./src/window/SimpleCalendarCreator.cpp \
    ./src/window/object_editor/EditRectangle.cpp
FORMS += ./src/window/object_editor/EditLine.ui \
    ./src/window/CalendarResizer.ui \
    ./src/window/ObjectCreator.ui \
    ./src/window/PreviewWindow.ui \
    ./src/window/SimpleCalendarCreator.ui \
    ./src/window/object_editor/EditRectangle.ui
RESOURCES += SimpleCalendarCreator.qrc
