# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/element/Dates.hpp \
    ./src/element/WeakTitle.hpp \
    ./src/element/MonthTitle.hpp \
    ./src/element/TemplatedText.hpp \
    ./src/element/Text.hpp \
    ./src/command/ChangeObjectProperties.hpp \
    ./src/element/Ellipse.hpp \
    ./src/element/Rectangle.hpp \
    ./src/element/CalendarObjectFactory.hpp \
    ./src/command/ResizeCalendar.hpp \
    ./src/command/UndoHistory.hpp \
    ./src/element/Line.hpp \
    ./src/command/AddObject.hpp \
    ./src/command/Command.hpp \
    ./src/command/RemoveObject.hpp \
    ./src/element/CustomListWidgetItem.hpp \
    ./src/element/Element.hpp \
    ./src/window/SimpleCalendarCreator.hpp \
    ./src/window/object_editor/EditDates.hpp \
    ./src/window/object_editor/EditWeakTitle.hpp \
    ./src/window/EditProjectInfo.hpp \
    ./src/window/object_editor/EditMonthTitle.hpp \
    ./src/window/object_editor/EditTemplatedText.hpp \
    ./src/window/object_editor/EditText.hpp \
    ./src/window/object_editor/EditRectangle.hpp \
    ./src/window/object_editor/EditEllipse.hpp \
    ./src/window/object_editor/EditLine.hpp \
    ./src/command/object_properties_modifier/LineObject.hpp \
    ./src/window/PreviewWindow.hpp \
    ./src/window/CalendarResizer.hpp \
    ./src/window/ObjectCreator.hpp \
    ./resource.h \
    ./src/window/About.hpp
SOURCES += ./src/element/Dates.cpp \
    ./src/element/WeakTitle.cpp \
    ./src/window/EditProjectInfo.cpp \
    ./src/element/MonthTitle.cpp \
    ./src/element/TemplatedText.cpp \
    ./src/element/Text.cpp \
    ./src/window/object_editor/EditDates.cpp \
    ./src/window/object_editor/EditEllipse.cpp \
    ./src/element/Ellipse.cpp \
    ./src/window/object_editor/EditMonthTitle.cpp \
    ./src/window/object_editor/EditRectangle.cpp \
    ./src/command/object_properties_modifier/LineObject.cpp \
    ./src/element/CalendarObjectFactory.cpp \
    ./src/element/Rectangle.cpp \
    ./src/window/object_editor/EditLine.cpp \
    ./src/command/ResizeCalendar.cpp \
    ./src/command/UndoHistory.cpp \
    ./src/window/CalendarResizer.cpp \
    ./src/element/Line.cpp \
    ./src/window/ObjectCreator.cpp \
    ./src/command/AddObject.cpp \
    ./src/command/RemoveObject.cpp \
    ./src/element/CustomListWidgetItem.cpp \
    ./src/main.cpp \
    ./src/window/object_editor/EditTemplatedText.cpp \
    ./src/window/object_editor/EditText.cpp \
    ./src/window/object_editor/EditWeakTitle.cpp \
    ./src/window/PreviewWindow.cpp \
    ./src/window/SimpleCalendarCreator.cpp \
    ./src/window/About.cpp
FORMS += ./src/window/EditProjectInfo.ui \
    ./src/window/object_editor/EditDates.ui \
    ./src/window/object_editor/EditEllipse.ui \
    ./src/window/object_editor/EditMonthTitle.ui \
    ./src/window/object_editor/EditRectangle.ui \
    ./src/window/object_editor/EditLine.ui \
    ./src/window/CalendarResizer.ui \
    ./src/window/ObjectCreator.ui \
    ./src/window/object_editor/EditTemplatedText.ui \
    ./src/window/object_editor/EditText.ui \
    ./src/window/object_editor/EditWeakTitle.ui \
    ./src/window/PreviewWindow.ui \
    ./src/window/SimpleCalendarCreator.ui \
    ./src/window/About.ui
RESOURCES += SimpleCalendarCreator.qrc
